# Generated by Django 4.2.2 on 2023-06-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdirector',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='backend\\cdc_app\x07pp\\director_profiles'),
        ),
        migrations.AddField(
            model_name='placementofficer',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='backend\\cdc_app\x07pp\\officer_profiles'),
        ),
    ]
