# Generated by Django 4.2.2 on 2023-06-14 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_placementdirector_profile_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('company', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('HR_name', models.CharField(max_length=50)),
                ('HR_mail', models.EmailField(max_length=254)),
                ('drive_mode', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('placement_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.placementofficer', to_field='staff_id')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
