# Generated by Django 4.2.2 on 2023-06-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='visibility',
            field=models.DateField(default=None, null=True),
        ),
    ]
