# Generated by Django 4.2.2 on 2023-06-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_drive_title_drive_id_drive_job_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='file',
            field=models.FileField(null=True, upload_to='backend\\cdc_app\x07pp\\elgible_lists'),
        ),
    ]
