# Generated by Django 4.2.2 on 2023-06-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_drive_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='status',
            field=models.CharField(default='Upcoming', max_length=50),
        ),
    ]
