# Generated by Django 4.2.2 on 2023-06-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_drive_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='placement_officer_id',
        ),
    ]
