# Generated by Django 4.2.2 on 2023-06-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_drive_placement_officer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='placement_officer_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
