# Generated by Django 4.2.2 on 2023-06-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_drive_placement_officer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='file',
            field=models.FileField(null=True, upload_to='https://drive.google.com/drive/folders/1K-nQH5nTwfF9lRXm2cAllFoqhaciQlA9?usp=drive_link'),
        ),
    ]
