# Generated by Django 4.2.2 on 2023-06-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_drive_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='file',
            field=models.FileField(null=True, upload_to='file_uploads/'),
        ),
    ]
