# Generated by Django 4.2.2 on 2023-06-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_drive_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='status',
        ),
    ]
