# Generated by Django 4.2.2 on 2023-06-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_drive_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='website',
        ),
    ]
