# Generated by Django 4.2.2 on 2023-06-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_report_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='placement_officer_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
