# Generated by Django 4.2.2 on 2023-06-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_report_placement_officer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='visibility',
            field=models.CharField(default='public', max_length=50),
        ),
    ]
