# Generated by Django 4.2.2 on 2023-06-19 06:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_report_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='visibile_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
