# Generated by Django 4.2.2 on 2023-06-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_report_visibile_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='visibile_to',
            new_name='visible_to',
        ),
    ]
