# Generated by Django 4.2.2 on 2023-06-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_visibile_to_report_visible_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
