# Generated by Django 4.2.2 on 2023-06-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_drive_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
