# Generated by Django 4.2.2 on 2023-06-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_drive_departments_report_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('HR_name', models.CharField(max_length=50)),
                ('HR_mail', models.EmailField(max_length=254)),
                ('placement_officer_id', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50, null=True)),
                ('website', models.URLField(null=True)),
            ],
        ),
    ]
