# Generated by Django 4.2.2 on 2023-06-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_reminder_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
