# Generated by Django 4.2.2 on 2023-06-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_report_hr_mail_remove_report_hr_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='contact_mode',
        ),
    ]
