# Generated by Django 4.2.2 on 2023-06-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_report_contact_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='HR_contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lock_hr_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='lock_hr_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
