# Generated by Django 4.2.2 on 2023-06-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_company_hr_contact_company_lock_hr_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='time',
        ),
    ]
