# Generated by Django 4.2.2 on 2023-06-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_report_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-timestamp']},
        ),
    ]
