# Generated by Django 4.2.2 on 2023-06-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_company_initiated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='HR_mail',
        ),
        migrations.RemoveField(
            model_name='drive',
            name='HR_name',
        ),
        migrations.RemoveField(
            model_name='drive',
            name='category',
        ),
        migrations.RemoveField(
            model_name='drive',
            name='placement_officer_id',
        ),
        migrations.RemoveField(
            model_name='drive',
            name='website',
        ),
    ]
