# Generated by Django 4.2.2 on 2023-07-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_studentedu_board_10_alter_studentedu_mark_10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drive',
            old_name='students',
            new_name='attended_students',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='drives',
            new_name='attended_drives',
        ),
        migrations.RemoveField(
            model_name='drive',
            name='file',
        ),
    ]
