# Generated by Django 4.2.2 on 2023-07-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_students_drive_attended_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='ctc',
            field=models.FloatField(null=True),
        ),
    ]
