# Generated by Django 4.2.2 on 2023-07-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_student_placement_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='filter_criteria',
            field=models.JSONField(null=True),
        ),
    ]
