# Generated by Django 4.2.2 on 2023-07-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_drive_filter_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='rounds',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='driveselection',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
