# Generated by Django 4.2.2 on 2023-07-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_drive_drive_rounds_drive_filter_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
