# Generated by Django 4.2.2 on 2023-07-21 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_drive_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveselection',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
