# Generated by Django 4.2.2 on 2023-07-24 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_driveselection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
