# Generated by Django 4.2.2 on 2023-12-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_report_remarks_alter_report_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=10)),
                ('appointment_id', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=50)),
                ('ctc', models.FloatField(null=True)),
                ('offer_letter_link', models.URLField(null=True)),
            ],
        ),
    ]
